apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld-appset
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              workloadcluster: "true"
      - git:
          repoURL: https://github.com/fperearodriguez/multicluster-canary.git
          revision: kvm-k8s
          directories:
          - path: argocd-resources/helloworld/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/fperearodriguez/multicluster-canary.git
        targetRevision: kvm-k8s
        path: argocd-resources/helloworld/{{path.basenameNormalized}}
      destination:
        namespace: helloworld
        server: '{{server}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
