apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld-canary
  name: helloworld-v2
  namespace: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld-canary
  template:
    metadata:
      labels:
        app: helloworld-canary
    spec:
      containers:
      - image: docker.io/istio/examples-helloworld-v2
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
      serviceAccountName: helloworld
