apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-spring-boot
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          workload: "true"
  template:
    metadata:
      name: 'helloworld-v1' # (2)
    spec:
      project: default
      source: # (3)
        repoURL: https://github.com/edubonifs/multicluster-canary.git
        targetRevision: HEAD
        path: argo-resources/application-set/helloworld-v1
      destination:
        server: '{{server}}' # (4)
        namespace: helloworld # (5)
      syncPolicy: # (6)
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
