apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-canary
spec:
  host: helloworld-canary.helloworld.svc.cluster.local
  subsets:
  - name: v2
    labels:
      version: v2