apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: istio-system
spec:
  hosts:
  - helloworld-k8s-1.fperod.internal
  - helloworld-k8s-2.fperod.internal
  gateways:
  - ingressgateway
  http:
  - name: helloworld-stable
    match:
    - uri:
        prefix: /hello
    route:
    - destination:
        host: helloworld.helloworld.svc.cluster.local
        port:
          number: 5000
    - destination:
        host: helloworld-canary.helloworld.svc.cluster.local
        port:
          number: 5000
      weight: 0